# Generated by Django 5.2.1 on 2025-06-04 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.URLField(blank=True, help_text="Inserisci qui l'URL dell'immagine", max_length=9999)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('Travel', 'travel'), ('Finanza', 'finanza'), ('Sport', 'sport'), ('Hobby', 'hobby'), ('Outfit', 'outfit'), ('Food', 'food'), ('Idea', 'idea'), ('Project', 'project')], default='altro', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
